




Select  OT_Codigo AS OT , ART_CodigoArticulo AS ARTICULO, ART_Nombre AS PRODUCTO, Cast(ISNULL(SOT_Recibido-SOT_Entregado, OTDA_Cantidad) as decimal(16,2)) AS CANT, CMUM_Nombre AS UNIDAD, ART_Comentarios AS DESCRIPCION, (Select AET_Valor from ArticulosEspecificaciones Where AET_ART_ArticuloId = ART_ArticuloId and AET_CMM_ArticuloEspecificaciones = 'CADE29BF-1459-4C9E-9A66-DA478E96D5E7') AS MEDIDA, (Select AET_Valor from ArticulosEspecificaciones Where AET_ART_ArticuloId = ART_ArticuloId and AET_CMM_ArticuloEspecificaciones = 'CE6EB5D1-7298-432E-94E5-2EB23D431C78') AS AREA, (Select AET_Valor from ArticulosEspecificaciones Where AET_ART_ArticuloId = ART_ArticuloId and AET_CMM_ArticuloEspecificaciones = '2ACE7D3D-734B-4603-B7C9-48E32FA7312E') AS ACABADOS, (Select AET_Valor from ArticulosEspecificaciones Where AET_ART_ArticuloId = ART_ArticuloId and AET_CMM_ArticuloEspecificaciones = '0DDB36A5-E60A-447A-8F22-D65C08886E8F') AS TELAS, 
ART_Imagen AS IMAGEN, PRY_NombreProyecto AS PROYECTO, Cast(OT_FechaOT as date) AS FECHA_DE_ENTREGA, Case When SOI_ID is null then 'PLANIFICADA' Else 'LIBERADA' end AS ESTATUS, Case When CET_Codigo is null then 'LIBERA2' Else CET_Codigo + '  ' + CET_Nombre + ' / ' + DEP_Nombre end AS ESTA2, Cast((OVD_PrecioUnitario / 5000) * OVD_CantidadRequerida as decimal(16,3)) AS PUNTOS, OV_CodigoOV AS OV, Cast(OVD_PrecioUnitario as decimal(16,2)) AS PRECIO_U, Cast(OV_FechaOV as date) AS FECH_OV From OrdenesTrabajo inner join OrdenesTrabajoDetalleArticulos on OT_OrdenTrabajoId = OTDA_OT_OrdenTrabajoId inner join Articulos on ART_ArticuloId = OTDA_ART_ArticuloId inner Join ControlesMaestrosUM on ART_CMUM_UMInventarioId = CMUM_UnidadMedidaId inner join OrdenesTrabajoReferencia on  OT_OrdenTrabajoId = OTRE_OT_OrdenTrabajoId inner join OrdenesVenta on OV_OrdenVentaId = OTRE_OV_OrdenVentaId 
inner join OrdenesVentaDetalle on OVD_OV_OrdenVentaId =OV_OrdenVentaId and OTDA_ART_ArticuloId = OVD_ART_ArticuloId inner join OrdenesVentaReq on OVR_OVD_DetalleId = OVD_DetalleId inner join Proyectos on OV_PRO_ProyectoId  = PRY_ProyectoId inner Join Clientes on OV_CLI_ClienteId = CLI_ClienteId Left Join RPT_Seguimiento_OTI on OTDA_OT_OrdenTrabajoId = SOI_OT Left Join RPT_Seguimiento_OT on  SOI_OT = SOT_OT Left Join CentrosTrabajo on CET_Codigo = SOT_Estacion and CET_Activo = 1 and CET_Borrado = 0 Left Join Departamentos on DEP_DeptoId = CET_DEP_DeptoId and DEP_Eliminado = 0 and DEP_Activo = 1 Where ( OT_CMM_Estatus = '3C843D99-87A6-442C-8B89-1E49322B265A' or OT_CMM_Estatus = 'A488B27B-15CD-47D8-A8F3-E9FB8AC70B9B' or OT_CMM_Estatus = '213ED3B9-12B3-41C9-8C6E-230DC86BBF90' ) and OT_Eliminado = 0  Order By OVR_FechaRequerida, OT_Codigo


