-- Consulta para 007 Catalogo de Articulos Materiales y Refacciones.
-- Objetivo: Presentar Relacion de Articulos que no son PT.
-- Desarrollado: Ing. Vicente Cueva R.
-- Actualizado: Sabado 21 de Abril del 2018; Origen
-- Actualizado: Sabado 03 de Noviembre del 2018; Cambio a MULIIX

-- DESARROLLO DE LA CONSULTA.

Select	top (10) ART_Articuloid as ID,
		ART_CodigoArticulo as CODIGO, 
		ART_Nombre as NOMBRE, 
		AFAM_Nombre as FAMILIA, 
		ACAT_Nombre as CATEGORIA, 
		SBC.CMM_Valor as SUB_CAT, 
		ATP_Descripcion as TIPO, 
		CMUM_Nombre as UM_Inv,
		Convert(Decimal(28,10), ART_CostoMaterialEstandar) AS ESTANDAR, 
		Convert(Decimal(28,10), ART_UltimoCostoUltimo) AS ULT_COMPRA, 
		CFI.CMM_DefinidoPorUsuario1 AS CODE_SAT, 
		CFI.CMM_Valor AS SAT_DESC, 
		ART_Activo As ACTIVO_1 
		, ART_ARTM_MarcaId
		, ATP_TipoId
from Articulos 
left join ArticulosFamilias on ART_AFAM_FamiliaId = AFAM_FamiliaId 
left join ArticulosCategorias on ART_ACAT_CategoriaId= ACAT_CategoriaId 
left join ArticulosTipos on ART_ATP_TipoId = ATP_TipoId 
left join ControlesMaestrosUM on ART_CMUM_UMInventarioId = CMUM_UnidadMedidaId 
left join ControlesMaestrosMultiples SBC on ART_CMM_SubcategoriaId = SBC.CMM_ControlId 
left join ControlesMaestrosMultiples CFI on ART_CMM_ClaveProductoId = CFI.CMM_ControlId 
where ART_Activo = 0 and ART_Eliminado = 0
--AND ATP_Descripcion = 'P.T Fabricado' 
and ART_CodigoArticulo = '05190'
order by ART_Nombre 


Select ART_CMM_SubcategoriaId, * from Articulos

Select * from ControlesMaestrosUM 

Select CMM_ControlId, CMM_Control, CMM_Valor from ControlesMaestrosMultiples -- Where CMM_ControlId = 'E8A9CE6B-6E87-4CEE-B054-EAD3A170365D'
Where  CMM_Control = 'CMM_INV_PoliticaOrden'
Where  CMM_Control = 'CMM_INV_ManejoInventario'
Where  CMM_Control = 'CMM_INV_SubcategoriaArticulos' --CMM_ControlId = '60CBCB45-18E6-495F-A302-5E42858D25FD'

Select * from ControlesMaestrosMultiples 
--Where CMM_DefinidoPorUsuario1 = '52131501'
Where CMM_DefinidoPorUsuario1 = '11162100'


--Where CMM_Control = 'CMM_CCXC_CFDIClaveProducto'
where CMM_Valor = 'Cortinas'


Select AFAM_FamiliaId,	AFAM_Nombre,	AFAM_Descripcion from ArticulosFamilias

Select ATP_TipoId, ATP_Descripcion, ATP_Etiqueta from ArticulosTipos


Select ARTM_MarcaId, ARTM_Codigo, ARTM_Nombre from ArticulosMarcas

Select ACAT_CategoriaId, ACAT_Nombre, ACAT_Descripcion from ArticulosCategorias


-- Consulta para pasar un articulo a Inactivo.

--Select ART_CodigoArticulo, ART_Nombre, ART_Activo, ART_Eliminado
--From Articulos
--Where ART_CodigoArticulo = '09970'


--Update Articulos Set ART_Activo = 0 Where ART_CodigoArticulo = '09970'


/*

--Select *
--from Articulos 
--Where ART_ATP_TipoId <> '56B66D49-FE82-4414-A7E8-43F3916572D3' --   Subensamble fabricado
--and ART_CodigoArticulo LIKE 'PLA%'



--Select *
--from Articulos 
--Where ART_CodigoArticulo LIKE 'PLA-EM%'
--AND ART_ATP_TipoId = '56B66D49-FE82-4414-A7E8-43F3916572D3' --   Subensamble fabricado


--Select * from Articulos Where ART_ArticuloId = '1F3D04BD-D675-4B3C-8055-10F60281E54A'

 --Los SUB (PLANTILLAS) Materias Primas se cambio a PT 30/mar/19 
--Update Articulos Set	ART_ATP_TipoId = '56B66D49-FE82-4414-A7E8-43F3916572D3',
--						ART_LOC_LocPredEntradasId = '62EAAF01-1020-4C75-9503-D58B07FFC6EF',
--						ART_LOC_LocPredSalidasId = '62EAAF01-1020-4C75-9503-D58B07FFC6EF',
--						ART_AFAM_FamiliaId = '53BD82CE-5F59-4CBA-85F7-ACD7C65603A5',
--						ART_ACAT_CategoriaId = 'B55DA558-AA83-4D0F-8A55-9415FDCAADF1',
--						ART_CMM_SubcategoriaId = '89A1F41F-B4D6-49D2-8179-4CF1EC64D7E4'
--Where ART_ATP_TipoId = '56B66D49-FE82-4414-A7E8-43F3916572D3' --   Subensamble fabricado
--and ART_CodigoArticulo LIKE 'PLA%'




-- Para Borrar un articulo hay que ponerle Activo 1 y Eliminado 1
--Select *
--from Articulos 
--Where ART_ArticuloId = '1CD93D1B-8790-4F54-B14A-2DE778CE42DA'

--Update Articulos set ART_Activo = 0, ART_Eliminado = 1 Where ART_ArticuloId = '1CD93D1B-8790-4F54-B14A-2DE778CE42DA'


-- Para cambio de Codigo de Aticulos 


Select	--ART_Articuloid as ID,
		ART_CodigoArticulo as CODIGO, 
		ART_Nombre as NOMBRE,
		ATP_Descripcion as TIPO,
		ART_FechaCreacion as CREADO,
		ART_SeguimientoLocMult as LOTES
from Articulos 
left join ArticulosTipos on ART_ATP_TipoId = ATP_TipoId 
where ART_Activo = 1 and ART_Eliminado = 0
AND ATP_Descripcion = 'Materia prima'
and ART_SeguimientoLocMult = 0
--and ART_CodigoArticulo = '12046'
order by ART_CodigoArticulo 


-- MATERIA PRIMA (PARA HACER EXCEPCION DE QUE SOLO SE USEN ESTOS DOS)
--AND ATP_Descripcion = 'Materia prima'
--and ATP_Descripcion = 'Consignado valor no contable'


-- PRODUCTO TERMINADO (PARA HACER EXCEPCIONES)
--and ATP_Descripcion = 'P.T Fabricado'
--and ATP_Descripcion = 'Subensamble fabricado'



--Select ART_CodigoArticulo from Articulos where ART_ArticuloId = '723B9737-AA30-41D7-A82F-661FD6EB39B1'
--update Articulos set ART_CodigoArticulo = 'C0075' where ART_ArticuloId = 'ACE8B2BF-34C0-47DE-8BFF-9BDD0E20179C'
*/

-- Cambiar articulos a Inactivos solicitados por Diana Mireles Miercoles 26 de Julio del 2023.

Select	ART_CodigoArticulo as CODIGO 
		, ART_Nombre as NOMBRE
		, ART_Activo AS ACTIVO
from Articulos  
where ART_CodigoArticulo = '10020'

Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10020'

Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10021'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10022'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10028'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10029'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10030'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10073'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10089'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10090'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10091'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10092'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10093'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10094'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10095'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10198'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10199'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10200'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10201'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10202'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10203'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10204'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10205'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10206'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10208'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10210'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10211'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10212'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10214'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10216'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10218'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10357'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10358'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10359'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10360'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10361'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10421'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10422'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11132'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11227'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11228'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11309'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11310'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11378'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11401'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11402'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11428'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11429'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11430'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11431'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11469'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11515'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11522'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11523'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11524'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11525'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11597'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11601'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11602'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11604'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11605'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11617'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11623'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11624'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11724'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11725'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11761'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11762'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11763'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11778'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11780'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12070'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12071'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12073'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12112'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12117'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12123'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12132'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12136'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12148'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12151'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12152'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12188'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12380'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12405'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12422'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12542'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12543'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12544'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12546'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12547'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12548'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12549'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12550'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12551'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12552'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12553'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12554'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12555'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12557'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12558'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12559'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12560'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12564'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12567'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12568'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12569'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12570'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12571'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12572'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12598'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12649'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12650'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12651'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12652'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12658'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12659'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12660'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12707'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12718'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12732'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12733'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12734'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12735'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12736'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12819'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12820'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12821'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12834'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12837'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12934'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12945'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12946'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13063'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13111'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13112'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13113'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13114'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13143'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13144'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13145'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13146'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13147'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13195'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13231'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13407'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13408'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13624'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13625'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13650'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01231'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01323'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01634'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01648'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01774'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '07960'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08495'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08611'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08625'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08626'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08636'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08673'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08674'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08701'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08702'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08709'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08722'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08723'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08777'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08863'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08905'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08906'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08907'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08908'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08909'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08910'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08911'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08912'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08922'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08979'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08983'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09292'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09321'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09331'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09333'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09399'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09458'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09459'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09682'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09683'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09684'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09685'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09686'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09687'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09688'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09689'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09690'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09691'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09692'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09693'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09694'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09695'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09696'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09824'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09836'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09837'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09855'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09889'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09890'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09902'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09903'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09904'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09928'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09930'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09931'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09932'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09933'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11378'



Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11583'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11584'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13187'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11578'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13172'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13170'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12485'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12487'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12484'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12789'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12335'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12287'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11129'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12537'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11119'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09874'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12379'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11779'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08845'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '07047'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08610'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11122'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11042'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11700'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11701'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11669'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13537'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09365'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12258'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08769'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08770'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10008'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '07581'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10903'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08607'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11356'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11356'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '02533'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '06341'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '03764'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '03853'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08658'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09843'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09843'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11697'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08679'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08741'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12206'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12204'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12190'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12539'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12191'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08542'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '06741'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08265'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '07946'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '07946'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11291'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11291'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10322'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11532'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11655'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11480'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11481'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01117'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01117'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11690'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12898'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13088'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09854'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11563'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11820'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '03411'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08659'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '03738'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09192'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08653'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08653'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10009'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09191'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10620'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10620'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10983'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10983'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11886'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11769'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01625'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '06493'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '06493'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '06493'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '02931'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '02931'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11850'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10982'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08582'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12480'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13222'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08822'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10822'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11883'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11873'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11873'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08360'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09432'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09434'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09429'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12696'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12697'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12445'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12444'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11849'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08359'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08361'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09936'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '05230'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '05230'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10301'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11477'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11640'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11643'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10007'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11644'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11871'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09841'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11872'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01381'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '04849'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11649'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11650'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11649'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12684'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12308'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12308'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09949'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11645'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11659'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11658'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09410'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08705'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08706'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11348'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11572'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08656'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11653'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11652'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10429'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10430'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08666'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09943'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08805'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11223'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10105'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10300'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11646'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11646'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09877'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11642'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10299'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12850'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11138'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09507'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11137'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09848'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09350'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10471'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09838'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12682'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08900'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11790'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11077'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11225'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11476'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09948'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12330'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12331'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12333'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09448'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '05221'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '05221'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09449'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10313'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10310'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09450'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10259'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10259'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09437'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09929'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09937'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09447'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12442'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13353'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12328'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12329'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12332'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12382'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08718'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12119'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11898'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10511'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12709'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08830'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10068'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12576'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12624'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10220'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13597'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '00126'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '00126'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12234'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10221'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13148'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09324'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12283'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13061'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08950'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11447'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12787'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09294'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11160'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11479'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12788'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10414'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12137'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12922'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09383'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09840'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12693'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '03800'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11668'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09939'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13196'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12161'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13286'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12663'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13135'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13174'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12641'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12458'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11841'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11841'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11124'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12593'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11334'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11573'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13490'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09440'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08901'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09482'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13641'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11708'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11707'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13390'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13313'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09483'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09373'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10059'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12656'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12675'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13165'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13164'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13163'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10025'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10023'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10024'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10056'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10052'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12863'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08827'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09972'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01756'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13444'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12114'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09411'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13602'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13601'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13657'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13656'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13655'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13369'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13437'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13248'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13446'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13477'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13654'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13498'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13295'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12853'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13045'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13046'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13324'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11714'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11213'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11212'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13553'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13542'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11799'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11798'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13370'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13296'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08689'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08688'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08690'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08691'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13049'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13639'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13249'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13366'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08781'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08779'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08780'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08732'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08731'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11594'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09917'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13545'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13620'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12739'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12436'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11575'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10302'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11648'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11662'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11391'

Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01632'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09996'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10509'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12093'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10026'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12481'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12300'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13237'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13233'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09971'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12469'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12468'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12471'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12470'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12890'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13244'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12891'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12892'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13567'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13568'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13566'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13569'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13570'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13571'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13572'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11706'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12802'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13311'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13255'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13256'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13246'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13108'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13257'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13258'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13555'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13556'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13245'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12209'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12208'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12207'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13312'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12298'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13238'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11167'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13033'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12538'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12284'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12277'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12264'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12269'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12281'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12267'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12270'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12273'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12274'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12280'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12276'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12266'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12278'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12265'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12272'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12275'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12271'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12279'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12268'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13016'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13136'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11411'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12165'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12040'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08665'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '01380'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09351'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11930'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11932'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11933'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11931'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09549'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11699'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11211'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08837'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13009'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12785'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12913'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12916'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12911'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12915'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12912'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12730'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11249'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12536'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11164'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12532'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12434'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13532'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12534'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10067'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11354'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11383'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11246'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11808'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10472'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08357'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12527'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08807'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11398'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08810'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08583'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13374'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10431'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10432'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13197'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09944'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10298'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13081'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09940'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09946'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13080'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11783'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11784'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11785'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11786'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11787'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11788'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11789'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10952'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08584'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08586'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12131'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12870'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11901'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11901'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08990'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09898'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09362'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09349'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09474'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09386'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09388'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12877'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12823'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '03906'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10461'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12449'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11498'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12685'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12686'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12141'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12540'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12370'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12371'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12372'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09509'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11581'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11395'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11393'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11381'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11385'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11397'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11392'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11396'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11382'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11728'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11728'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11467'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10295'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11656'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11657'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11466'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12692'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13269'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10470'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11703'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11705'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11384'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11390'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11394'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10303'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11579'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11809'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09389'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '02631'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '04527'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '02629'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09835'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10736'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09950'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11387'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11387'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11388'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12689'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12690'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12924'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12930'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12925'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12931'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12738'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12691'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12683'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09938'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12869'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '04118'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11553'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11552'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11907'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13059'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12364'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12847'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12754'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12634'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12874'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11569'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12873'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11570'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11509'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11269'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12438'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11237'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12158'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12159'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12160'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10460'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08982'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12792'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '05684'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11543'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08660'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11846'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11482'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12225'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10415'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13645'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10144'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10145'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10147'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11571'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13539'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10139'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10182'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10131'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10183'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10178'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10132'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10179'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10180'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10176'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10181'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10185'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10189'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10177'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10184'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10188'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10187'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10370'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10133'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10150'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10153'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10166'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10171'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10171'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10172'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10172'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10159'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10173'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10156'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10154'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10148'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10149'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10163'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10164'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10160'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10165'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10162'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13121'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12589'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12594'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12583'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12584'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12596'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12585'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11324'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11323'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11322'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11716'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11818'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11406'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11405'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11407'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11408'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11333'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11320'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11321'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11336'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12239'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12263'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11338'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11337'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11339'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11676'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11416'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11566'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11340'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13019'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11428'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12934'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12136'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11161'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12652'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13195'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12405'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13011'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13011'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13035'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12655'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11239'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13287'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13305'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13149'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13166'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08953'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13621'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10508'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10506'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10507'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10479'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10477'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08708'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '06078'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12115'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12851'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12078'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08959'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13540'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11926'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12406'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09445'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09446'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13630'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12518'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12533'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11350'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13306'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12437'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09329'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08952'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08635'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12671'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12670'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08957'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13515'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '05165'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11742'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11243'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13085'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08664'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08767'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08978'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08996'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09845'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12984'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13162'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '05869'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12767'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12441'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '13216'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '08931'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11720'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12259'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10219'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11989'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09289'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10222'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11497'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11496'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '09505'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '12688'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11386'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11654'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11660'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11660'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11639'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10253'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10434'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10433'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10473'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '10296'
Update Articulos set ART_Activo = 0 Where ART_CodigoArticulo = '11379'








