-- Reporte de Disponibilidad de Telas.
-- Se quita la vista que se tenia de Vw_Disponibilidad_Piel y se reduce las columnas que no se utilizan.
-- Modificado por: Ing. vicente Cueva Ramirez.
-- Actualizado: Martes 30 de Marzo del 2021; Origen.

-- Consulta que une todas las informaciones.

Select	DISPON.CODIGO
		, DISPON.DESCRIPCION
		, DISPON.UDM
		, SUM(DISPON.EXISTENCIA) AS EXISTENCIA
		, SUM(DISPON.EN_PEDIDO) AS EN_PEDIDO
		, SUM(DISPON.PRIORIDAD1) AS PRIORIDAD1
		, SUM(DISPON.PRIORIDAD3) AS PRIORIDAD3
		, SUM(DISPON.PRIORIDAD6) AS PRIORIDAD6
		, SUM(DISPON.EXISTENCIA)-SUM(DISPON.EN_PEDIDO)-SUM(DISPON.PRIORIDAD1)-SUM(DISPON.PRIORIDAD3)-SUM(DISPON.PRIORIDAD6) AS DISPONIBLE
		, SUM(DISPON.OC_PEDIDO_PROVEEDOR) AS PEDIDO_PROVEEDOR
		, SUM(DISPON.EXISTENCIA)-SUM(DISPON.EN_PEDIDO)-SUM(DISPON.PRIORIDAD1)-SUM(DISPON.PRIORIDAD3)-SUM(DISPON.PRIORIDAD6) +
		  SUM(DISPON.OC_PEDIDO_PROVEEDOR) AS DISPONIBLE_GENERAL
		, DISPON.TE AS TE
		, DISPON.LINEA
FROM (

-- Determina la Existencia de los Articulos en AMP-ST y AMP-CC
Select	OITM.ItemCode AS CODIGO
		, OITM.ItemName AS DESCRIPCION
		, OITM.InvntryUom AS UDM
		, SUM(OITW.OnHand) AS EXISTENCIA
		, CONVERT(int, '0') AS EN_PEDIDO
		, CONVERT(int, '0') AS PRIORIDAD1
		, CONVERT(int, '0') AS PRIORIDAD3
		, CONVERT(int, '0') AS PRIORIDAD6
		, CONVERT(int, '0') AS OC_PEDIDO_PROVEEDOR                  
		, OITM.LeadTime AS TE
		, OITM.U_GrupoPlanea AS LINEA
FROM OITM 
INNER JOIN OITW ON OITW.ItemCode = OITM.ItemCode AND (OITW.WhsCode = 'AMP-ST' OR OITW.WhsCode = 'AMP-CC')
WHERE OITM.ItmsGrpCod = 114
GROUP BY OITM.ItemCode, OITM.ItemName, OITM.InvntryUom, OITW.WhsCode, OITM.LeadTime, OITM.U_GrupoPlanea

Union All
                          
-- Determina la Necesidad en Pedidos.						  
SELECT  OITM.ItemCode AS CODIGO
		, OITM.ItemName AS DESCRIPCION
		, OITM.InvntryUom AS UDM
		, CONVERT(INT, '0') AS EXISTENCIA
		, SUM(dbo.RDR1.OpenQty * dbo.ITT1.Quantity) AS EN_PEDIDO
		, CONVERT(INT, '0') AS PRIORIDAD1
		, CONVERT(int, '0') AS PRIORIDAD3
		, CONVERT(int, '0') AS PRIORIDAD6
		, CONVERT(INT, '0') AS OC_PEDIDOS_PROVEEDOR
		, OITM.LeadTime AS TE
		, OITM.U_GrupoPlanea AS LINEA
FROM ORDR 
INNER JOIN RDR1 ON RDR1.DocEntry = dbo.ORDR.DocEntry 
INNER JOIN ITT1 ON ITT1.Father = dbo.RDR1.ItemCode 
INNER JOIN OITM ON OITM.ItemCode = dbo.ITT1.Code 
WHERE (ORDR.U_Procesado = 'N') AND (ORDR.CANCELED = 'N') AND (RDR1.TreeType <> 'S') AND (RDR1.LineStatus = 'O') AND (OITM.ItmsGrpCod = 114)
GROUP BY OITM.ItemCode, OITM.ItemName, OITM.InvntryUom, OITM.InvntryUom, ORDR.DocDueDate
, dbo.ORDR.DocEntry, OITM.LeadTime, OITM.U_GrupoPlanea

Union all

-- Determina la Necesidad de Ordenes en Prioridad 1, Prioridad 3 y Prioridad 6.	
Select	OITM.ItemCode AS CODIGO
		, OITM.ItemName  AS DESCRIPCION
		, OITM.InvntryUom AS UDM
		, CONVERT(INT, '0') AS EXISTENCIA
		, CONVERT(INT, '0') AS EN_PEDIDO
		, SUM(CASE WHEN WOR1.IssuedQty > 0 THEN 0 ELSE CASE WHEN OWOR.U_C_Orden = 'C' THEN wor1.PlannedQty ELSE 0 END END) AS PRIORIDAD1
		, SUM(CASE WHEN WOR1.IssuedQty > 0 THEN 0 ELSE CASE WHEN OWOR.U_C_Orden = 'S' THEN wor1.PlannedQty ELSE 0 END END) AS PRIORIDAD3
		, SUM(CASE WHEN WOR1.IssuedQty > 0 THEN 0 ELSE CASE WHEN OWOR.U_C_Orden = 'P' THEN wor1.PlannedQty ELSE 0 END END) AS PRIORIDAD6
		,  CONVERT(INT, '0') AS OC_PEDIDO_PROVEEDOR 
		, OITM.LeadTime AS TE
		, OITM.U_GrupoPlanea AS LINEA
FROM OWOR 
INNER JOIN WOR1 ON WOR1.DocEntry = OWOR.DocEntry 
INNER JOIN OITM ON OITM.ItemCode = dbo.WOR1.ItemCode 
WHERE (OWOR.Status <> 'C') AND (OWOR.Status <> 'L') AND (OITM.ItmsGrpCod = 114)
GROUP BY OITM.ItemCode, OITM.ItemName, OITM.InvntryUom, OITM.LeadTime, OITM.U_GrupoPlanea

Union All

-- Pieles pedidas al Proveedor.
Select	POR1.ItemCode AS CODIGO 
		, OITM.ItemName AS DESCRIPCION
		, OITM.InvntryUom AS UDM
		, CONVERT(INT, '0') AS EXISTENCIA
		, CONVERT(INT, '0') AS EN_PEDIDO
		, CONVERT(INT, '0') AS PRIORIDAD1
		, CONVERT(int, '0') AS PRIORIDAD3
		, CONVERT(int, '0') AS PRIORIDAD6
		, SUM(POR1.OpenQty) AS OC_PEDIDO_PROVEEDOR
		, OITM.LeadTime AS TE
		, OITM.U_GrupoPlanea AS LINEA
From OPOR 
INNER JOIN POR1 ON POR1.DocEntry = OPOR.DocEntry 
INNER JOIN OITM ON OITM.ItemCode = POR1.ItemCode                           
WHERE (OPOR.CANCELED = 'N') AND (POR1.OpenQty > 0) AND (OITM.ItmsGrpCod = 114)
GROUP BY POR1.ItemCode, OITM.ItemName, OITM.InvntryUom, OITM.LeadTime, OITM.U_GrupoPlanea

) AS DISPON
Group By DISPON.CODIGO, DISPON.DESCRIPCION, DISPON.UDM, DISPON.TE, DISPON.LINEA
Order By DISPON.LINEA Desc, DISPON.DESCRIPCION

-- Fin de la Consulta...
  




  
Select	DISPON.CODIGO, DISPON.DESCRIPCION, DISPON.UDM, SUM(DISPON.EXISTENCIA) AS EXISTENCIA, SUM(DISPON.EN_PEDIDO) AS EN_PEDIDO, SUM(DISPON.PRIORIDAD1) AS PRIORIDAD1, SUM(DISPON.PRIORIDAD3) AS PRIORIDAD3, SUM(DISPON.PRIORIDAD6) AS PRIORIDAD6, SUM(DISPON.EXISTENCIA)-SUM(DISPON.EN_PEDIDO)-SUM(DISPON.PRIORIDAD1)-SUM(DISPON.PRIORIDAD3)-SUM(DISPON.PRIORIDAD6) AS DISPONIBLE, SUM(DISPON.OC_PEDIDO_PROVEEDOR) AS PEDIDO_PROVEEDOR, SUM(DISPON.EXISTENCIA)-SUM(DISPON.EN_PEDIDO)-SUM(DISPON.PRIORIDAD1)-SUM(DISPON.PRIORIDAD3)-SUM(DISPON.PRIORIDAD6) + SUM(DISPON.OC_PEDIDO_PROVEEDOR) AS DISPONIBLE_GENERAL, DISPON.TE AS TE, DISPON.LINEA FROM (Select	OITM.ItemCode AS CODIGO, OITM.ItemName AS DESCRIPCION, OITM.InvntryUom AS UDM, SUM(OITW.OnHand) AS EXISTENCIA, CONVERT(int, '0') AS EN_PEDIDO, CONVERT(int, '0') AS PRIORIDAD1, CONVERT(int, '0') AS PRIORIDAD3, 
CONVERT(int, '0') AS PRIORIDAD6, CONVERT(int, '0') AS OC_PEDIDO_PROVEEDOR, OITM.LeadTime AS TE, OITM.U_GrupoPlanea AS LINEA FROM OITM INNER JOIN OITW ON OITW.ItemCode = OITM.ItemCode AND (OITW.WhsCode = 'AMP-ST' OR OITW.WhsCode = 'AMP-CC') WHERE OITM.ItmsGrpCod = 114 GROUP BY OITM.ItemCode, OITM.ItemName, OITM.InvntryUom, OITW.WhsCode, OITM.LeadTime, OITM.U_GrupoPlanea Union All SELECT  OITM.ItemCode AS CODIGO, OITM.ItemName AS DESCRIPCION, OITM.InvntryUom AS UDM, CONVERT(INT, '0') AS EXISTENCIA, SUM(dbo.RDR1.OpenQty * dbo.ITT1.Quantity) AS EN_PEDIDO, CONVERT(INT, '0') AS PRIORIDAD1, CONVERT(int, '0') AS PRIORIDAD3, CONVERT(int, '0') AS PRIORIDAD6, CONVERT(INT, '0') AS OC_PEDIDOS_PROVEEDOR, OITM.LeadTime AS TE, OITM.U_GrupoPlanea AS LINEA FROM ORDR INNER JOIN RDR1 ON RDR1.DocEntry = dbo.ORDR.DocEntry INNER JOIN ITT1 ON ITT1.Father = dbo.RDR1.ItemCode 
INNER JOIN OITM ON OITM.ItemCode = dbo.ITT1.Code WHERE (ORDR.U_Procesado = 'N') AND (ORDR.CANCELED = 'N') AND (RDR1.TreeType <> 'S') AND (RDR1.LineStatus = 'O') AND (OITM.ItmsGrpCod = 114) GROUP BY OITM.ItemCode, OITM.ItemName, OITM.InvntryUom, OITM.InvntryUom, ORDR.DocDueDate, dbo.ORDR.DocEntry, OITM.LeadTime, OITM.U_GrupoPlanea Union all Select	OITM.ItemCode AS CODIGO, OITM.ItemName  AS DESCRIPCION, OITM.InvntryUom AS UDM, CONVERT(INT, '0') AS EXISTENCIA, CONVERT(INT, '0') AS EN_PEDIDO, SUM(CASE WHEN WOR1.IssuedQty > 0 THEN 0 ELSE CASE WHEN OWOR.U_C_Orden = 'C' THEN wor1.PlannedQty ELSE 0 END END) AS PRIORIDAD1, SUM(CASE WHEN WOR1.IssuedQty > 0 THEN 0 ELSE CASE WHEN OWOR.U_C_Orden = 'S' THEN wor1.PlannedQty ELSE 0 END END) AS PRIORIDAD3, SUM(CASE WHEN WOR1.IssuedQty > 0 THEN 0 ELSE CASE WHEN OWOR.U_C_Orden = 'P' THEN wor1.PlannedQty ELSE 0 END END) AS PRIORIDAD6
,  CONVERT(INT, '0') AS OC_PEDIDO_PROVEEDOR, OITM.LeadTime AS TE, OITM.U_GrupoPlanea AS LINEA FROM OWOR INNER JOIN WOR1 ON WOR1.DocEntry = OWOR.DocEntry INNER JOIN OITM ON OITM.ItemCode = dbo.WOR1.ItemCode WHERE (OWOR.Status <> 'C') AND (OWOR.Status <> 'L') AND (OITM.ItmsGrpCod = 114) GROUP BY OITM.ItemCode, OITM.ItemName, OITM.InvntryUom, OITM.LeadTime, OITM.U_GrupoPlanea Union All Select	POR1.ItemCode AS CODIGO, OITM.ItemName AS DESCRIPCION, OITM.InvntryUom AS UDM, CONVERT(INT, '0') AS EXISTENCIA, CONVERT(INT, '0') AS EN_PEDIDO, CONVERT(INT, '0') AS PRIORIDAD1, CONVERT(int, '0') AS PRIORIDAD3, CONVERT(int, '0') AS PRIORIDAD6, SUM(POR1.OpenQty) AS OC_PEDIDO_PROVEEDOR, OITM.LeadTime AS TE, OITM.U_GrupoPlanea AS LINEA From OPOR INNER JOIN POR1 ON POR1.DocEntry = OPOR.DocEntry INNER JOIN OITM ON OITM.ItemCode = POR1.ItemCode WHERE (OPOR.CANCELED = 'N') AND (POR1.OpenQty > 0) AND (OITM.ItmsGrpCod = 114)
GROUP BY POR1.ItemCode, OITM.ItemName, OITM.InvntryUom, OITM.LeadTime, OITM.U_GrupoPlanea ) AS DISPON Group By DISPON.CODIGO, DISPON.DESCRIPCION, DISPON.UDM, DISPON.TE, DISPON.LINEA Order By DISPON.LINEA Desc, DISPON.DESCRIPCION 




